name: Deploy to GitHub Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

env:
  NODE_ENV: production

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Setup Pages
        uses: actions/configure-pages@v4
        
      - name: Install dependencies
        run: |
          cd website/thought_organizer_website
          rm -f package-lock.json
          npm install
          npm install -D autoprefixer@10.4.16 postcss@8.4.32 tailwindcss@3.3.0
          rm -f postcss.config.js
          rm -f postcss.config.mjs
        
      - name: Build with Next.js
        run: |
          cd website/thought_organizer_website
          NODE_ENV=production npm run build
        env:
          NEXT_TELEMETRY_DISABLED: 1
        
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: website/thought_organizer_website/out

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4 